In [109]:
import numpy as np
subst_mat = np.array([
        [10,2,5,2],
        [2,10,2,5],
        [5,2,10,2],
        [2,5,2,10]
    ])


subst_mat[0,2]

5

In [110]:
def C(i,j):
    if T[i, j] == None:        
        dict_subst = {"A":0, "C": 1, "G":2, "T":3}
        v1,v2,v3,v4 = 0,0,0,0
        if i>0 and j>0 : 
            v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j)-5
        if i>=0 and j>0 : 
            v3 = C(i, j-1)-5
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = max(v1,v2,v3,v4)
    return T[i,j] 

In [111]:
seq1 = "AATAAT"
seq2 = "AAGG"

m = len(seq1)
n = len(seq2)

#T = np.empty((m-1,n-1)) * np.nan
T = np.full([m+1,n+1], None)

C(m,n)

22

In [112]:
import Bio

In [113]:
from Bio import SeqIO
import numpy as np

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

In [114]:
seq1 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq1.fasta").values())[0]
seq2 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq2.fasta").values())[0]
print(seq1)
print(seq2)

GGCCTAAAGGCGCCGGTCTTTCGTACCCCAAAATCTCGGCATTTTAAGATAAGTGAGTGTTGCGTTACACTAGCGATCTACCGCGTCTTATACTTAAGCGTATGCCCAGATCTGACTAATCGTGCCCCCGGATTAGACGGGCTTGATGGGAAAGAACAGCTCGTCTGTTTACGTATAAACAGAATCGCCTGGGTTCGC
GGGCTAAAGGTTAGGGTCTTTCACACTAAAGAGTGGTGCGTATCGTGGCTAATGTACCGCTTCTGGTATCGTGGCTTACGGCCAGACCTACAAGTACTAGACCTGAGAACTAATCTTGTCGAGCCTTCCATTGAGGGTAATGGGAGAGAACATCGAGTCAGAAGTTATTCTTGTTTACGTAGAATCGCCTGGGTCCGC


In [115]:
m = len(seq1)
n = len(seq2)

#T = np.empty((m-1,n-1)) * np.nan
T = np.full([m+1,n+1], None)

C(m,n)



1346

In [116]:
def C(i,j):
    if T[i, j] == None:        
        dict_subst = {"A":0, "C": 1, "G":2, "T":3}
        v1,v2,v3,v4 = 0,0,0,0
        if i>0 and j>0 :      #diagonal
            v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 :     #up
            v2 = C(i-1,j)-5
        if i>=0 and j>0 :    #left
            v3 = C(i, j-1)-5
        if i==0 and j==0 : 
            v4 = 0
        maximum = max(v1,v2,v3,v4)
        T[i,j] = maximum
        direction = ""
        if maximum == v1:
            direction = "diagonal"
        elif maximum == v2:
            direction = "up"
        elif maximum == v3:
            direction = "left"
        else:
            direction:"x"            
        BT[i,j] = direction
    return T[i,j] 

In [117]:
seq1 = "TCCAGAGA" 
seq2 = "TCGAT" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)
#The backtrack matrix
BT = np.full([m+1,n+1], None)

print(C(m,n))
print(T)
print(BT)


27
[[0 0 0 0 0 0]
 [0 10 5 2 2 10]
 [0 5 20 15 10 7]
 [0 5 15 22 17 15]
 [0 2 10 20 32 27]
 [0 2 5 20 27 34]
 [0 2 4 15 30 29]
 [0 2 4 14 25 32]
 [0 2 4 9 24 27]]
[['diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'left' 'left' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal']
 ['diagonal' 'diagonal' 'up' 'diagonal' 'diagonal' 'left']
 ['diagonal' 'diagonal' 'up' 'diagonal' 'up' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'up' 'diagonal' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'diagonal' 'up' 'diagonal']
 ['diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal' 'diagonal']]


In [118]:
#Backtracking from slides

def RecurBackTrack(i, j, align1, align2):
    print(align1)
    print(align2)
    dict_subst = {"A":0, "C": 1, "G":2, "T":3}
    if i>0 and j>0 and T[i, j] ==  T[i-1, j-1]+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]: 
            align1 = seq1[i]
            align2 = seq2[j]
            return RecurBackTrack(i-1, j-1, align1, align2)
    elif i>0 and j>=0 and T[i,j] == T[i-1,j] -5:
            align1 = seq1[i]
            align2 = "-"
            return RecurBackTrack(i-1, j, align1, align2)
    elif i>=0 and j>0 and T[i,j] == T[i,j-1] -5:
            align1 = "-"
            align2 = seq1[j]
            return RecurBackTrack(i, j-1, align1, align2)
    
RecurBackTrack(m,n, align1, align2)

IndexError: string index out of range

In [119]:
seq1 = "CGTGTCAAGTCT"
seq2 = "ACGTCGTAGCTAGG"

align1 = ""
align2 = ""

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

print(RecurBackTrack(m,n, align1, align2))



TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'