In [9]:
import numpy as np
subst_mat = np.array([
        [10,2,5,2],
        [2,10,2,5],
        [5,2,10,2],
        [2,5,2,10]
    ])

In [7]:
subst_mat[0,2]

5

In [32]:
def C(i,j):
    dict_subst = {"A":0, "C": 1, "G":2, "T":3}
    v1,v2,v3,v4 = 0,0,0,0
    if i>0 and j>0 : 
        v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
    if i>0 and j>=0 : 
        v2 = C(i-1,j)-5
    if i>=0 and j>0 : 
        v3 = C(i, j-1)-5
    if i==0 and j==0 : 
        v4 = 0
    return max(v1,v2,v3,v4) 

In [33]:
seq1 = "AATAAT"
seq2 = "AAGG"
C(len(seq1),len(seq2))

22

In [6]:
import Bio

In [8]:
from Bio import SeqIO

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

seq1 = list(read_FASTA("seq1.fasta").values())[0]
seq2 = list(read_FASTA("seq2.fasta").values())[0]
print(seq1)
print(seq2)

GGCCTAAAGGCGCCGGTCTTTCGTACCCCAAAATCTCGGCATTTTAAGATAAGTGAGTGTTGCGTTACACTAGCGATCTACCGCGTCTTATACTTAAGCGTATGCCCAGATCTGACTAATCGTGCCCCCGGATTAGACGGGCTTGATGGGAAAGAACAGCTCGTCTGTTTACGTATAAACAGAATCGCCTGGGTTCGC
GGGCTAAAGGTTAGGGTCTTTCACACTAAAGAGTGGTGCGTATCGTGGCTAATGTACCGCTTCTGGTATCGTGGCTTACGGCCAGACCTACAAGTACTAGACCTGAGAACTAATCTTGTCGAGCCTTCCATTGAGGGTAATGGGAGAGAACATCGAGTCAGAAGTTATTCTTGTTTACGTAGAATCGCCTGGGTCCGC


In [41]:
T = np.full([len(seq1), len(seq2)],None)
def C(i,j):
    dict_subst = {"A":0, "C": 1, "G":2, "T":3}
    if T[i,j]==None : 
        v1,v2,v3,v4 = 0,0,0,0
        if i>0 and j>0 : 
            v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j)-5
        if i>=0 and j>0 : 
            v3 = C(i, j-1)-5
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = max(v1,v2,v3,v4)
    return T[i,j]

In [71]:
seq1 = "CGTGTCAAGTCT"
seq2 = "ACGTCGTAGCTAGG"
T = np.full([len(seq1)+1, len(seq2)+1],None)
C(len(seq1),len(seq2))

66

In [58]:
seq1 = list(read_FASTA("seq1.fasta").values())[0]
seq2 = list(read_FASTA("seq2.fasta").values())[0]
T = np.full([len(seq1)+1, len(seq2)+1],None)
mat=C(len(seq1),len(seq2))

In [63]:
T

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 10, 10, ..., 2, 10, 5],
       [0, 10, 20, ..., 5, 12, 12],
       ...,
       [0, 2, 5, ..., 1326, 1321, 1316],
       [0, 10, 12, ..., 1321, 1336, 1331],
       [0, 5, 12, ..., 1321, 1331, 1346]], dtype=object)

In [82]:
def backtrack(mat, n, m, path1="", path2=""):
    if n==1 and m==1:
        return (path1,path2)
    elif n==1 :
        for i in range(m):
            path1+="_"
            path2+= seq2[m-i]
        return(path1, path2)
    elif m==1 : 
        for i in range(n):
            path1+=seq1[n-i]
            path2+="_"
        return(path1, path2)
    else :
        next_step = min(mat[n-1,m-1], mat[n-1,m], mat[n,m-1])
        if mat[n-1,m-1]==next_step :
            path1+=seq1[n]
            path2 += seq2[m]
            return backtrack(mat,n-1,m-1,path1,path2)
        if mat[n-1,m]==next_step :
            path1 += "_"
            path2 += seq2[m]
            return backtrack(mat,n-1,m,path1,path2)
        if mat[n,m-1]==next_step :
            path1 += "_"
            path2 += seq2[m]
            return backtrack(mat,n,m-1,path1,path2)

In [83]:
seq1 = "AATAAT" # len = 6
seq2 = "AAGG" # len = 4
T = np.full([len(seq1)+1, len(seq2)+1],None) # shape = (7,5)
mat = C(len(seq1),len(seq2))
print(mat, T)
backtrack(T, T.shape[0]-2, T.shape[1]-2)

22 [[0 0 0 0 0]
 [0 10 10 5 5]
 [0 10 20 15 10]
 [0 5 15 22 17]
 [0 10 15 20 27]
 [0 10 20 20 25]
 [0 5 15 22 22]]


('TAATA', 'GG___')

In [81]:
seq1[0]

'A'

In [89]:
def backtrack(mat, n, m):
    if n==1 and m==1:
        return B
    elif n==1 :
        for i in range(m-1):
            B[1,m-i]="left"
        return(B)
    elif m==1 : 
        for i in range(n-1):
            B[n-i,1]="up"
        return B
    else :
        next_step = min(mat[n-1,m-1], mat[n-1,m], mat[n,m-1])
        if mat[n-1,m-1]==next_step :
            B[n,m]="diag"
            return backtrack(mat,n-1,m-1)
        if mat[n-1,m]==next_step :
            B[n,m]="up"
            return backtrack(mat,n-1,m)
        if mat[n,m-1]==next_step :
            B[n,m]="left"
            return backtrack(mat,n,m-1)

In [94]:
seq1 = "AATAAT" # len = 6
seq2 = "AAGG" # len = 4
T = np.full([len(seq1)+1, len(seq2)+1],None) # shape = (7,5)
mat = C(len(seq1),len(seq2))
print(mat, T)
B = np.full([len(seq1)+1, len(seq2)+1],None)
B[1,1]= "Start"
mat = backtrack(T, T.shape[0]-1, T.shape[1]-1)

22 [[0 0 0 0 0]
 [0 10 10 5 5]
 [0 10 20 15 10]
 [0 5 15 22 17]
 [0 10 15 20 27]
 [0 10 20 20 25]
 [0 5 15 22 22]]


In [98]:
def read_align (mat):
    n,m=mat.shape[0]-1, mat.shape[1]-1
    i,j=1,1
    align1=""
    align2=""
    while (i,j)!=(n,m):
        if mat[i+1,j+1]=="diag":
            align1+=seq1[i]
            align2+=seq2[j]
            i+=1
            j+=1
        elif mat[i,m+1]=="left":
            align1+="_"
            align2 += seq2[m]
            j+=1
        elif mat[i-1,j]=="up":
            align1+= seq1[i]
            align2+="_"
            i+=1
    return (align1, align2)

In [99]:
read_align(mat)

IndexError: index 5 is out of bounds for axis 1 with size 5