In [43]:
import numpy as np
subst_mat = np.array([
        [10,2,5,2],
        [2,10,2,5],
        [5,2,10,2],
        [2,5,2,10]
    ])

In [44]:
def C(i,j):
    if T[i, j] == None:        
        dict_subst = {"A":0, "C": 1, "G":2, "T":3}
        v1,v2,v3,v4 = 0,0,0,0
        if i>0 and j>0 : 
            v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j)-5
        if i>=0 and j>0 : 
            v3 = C(i, j-1)-5
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = max(v1,v2,v3,v4)
    return T[i,j] 

In [69]:
def C(i,j):
    if T[i, j] == None:        
        dict_subst = {"A":0, "C": 1, "G":2, "T":3}
        v1,v2,v3,v4 = 0,0,0,0
        if i>0 and j>0 : 
            v1 = C(i-1,j-1)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j)-5
        if i>=0 and j>0 : 
            v3 = C(i, j-1)-5
        if i==0 and j==0 : 
            v4 = 0
        max_val = max(v1,v2,v3,v4)
        T[i,j] = max_val
        dir = ""
        if max_val == v1:
            dir = "dia"
        elif max_val == v2:
            dir = "up"
        elif max_val == v3:
            dir = "left"
        else:
            dir:"x"            
        B[i,j] = dir
    return T[i,j] 

In [70]:
seq1 = "TCCAGAGA"
seq2 = "TCGAT"

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)
#The backtrack matrix
B = np.full([m+1,n+1], None)

print(C(m,n))
print(T)
print(B)

27
[[0 0 0 0 0 0]
 [0 10 5 2 2 10]
 [0 5 20 15 10 7]
 [0 5 15 22 17 15]
 [0 2 10 20 32 27]
 [0 2 5 20 27 34]
 [0 2 4 15 30 29]
 [0 2 4 14 25 32]
 [0 2 4 9 24 27]]
[['dia' 'dia' 'dia' 'dia' 'dia' 'dia']
 ['dia' 'dia' 'dia' 'dia' 'dia' 'dia']
 ['dia' 'dia' 'dia' 'left' 'left' 'dia']
 ['dia' 'dia' 'dia' 'dia' 'dia' 'dia']
 ['dia' 'dia' 'up' 'dia' 'dia' 'left']
 ['dia' 'dia' 'up' 'dia' 'up' 'dia']
 ['dia' 'dia' 'dia' 'up' 'dia' 'dia']
 ['dia' 'dia' 'dia' 'dia' 'up' 'dia']
 ['dia' 'dia' 'dia' 'dia' 'dia' 'dia']]


In [71]:
#func to translate the backtrack
#print(n)
def get_alignment():
    alignseq1 = ""
    alignseq2 = ""
    i = m-1
    j = n-1
    while i>=0 & j >=0:
        if B[i,j] == "dia":
            alignseq1 += seq1[i]
            alignseq2 += seq2[j]
            i -= 1
            j -= 1
        elif B[i,j] == "up":
            alignseq1 += seq1[i]
            alignseq2 += "-"
            i -= 1
        else:
            alignseq1 += "-"
            alignseq2 += seq2[i]
            j -= 1
        print(alignseq1)
        print(alignseq2)
        print("STOP")
    print(alignseq1[::-1])
    print(alignseq2[::-1])
            
get_alignment()

A
-
STOP
AG
-T
STOP
AGA
-TA
STOP
AGAG
-TA-
STOP
AGAGA
-TA-G
STOP
AGAGAC
-TA-GC
STOP
AGAGACC
-TA-GCT
STOP
AGAGACCT
-TA-GCTT
STOP
TCCAGAGA
TTCG-AT-


In [38]:
import Bio

In [39]:
from Bio import SeqIO
import numpy as np

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

In [40]:
seq1 = list(read_FASTA("seq1.fasta").values())[0]
seq2 = list(read_FASTA("seq2.fasta").values())[0]
print(seq1)
print(seq2)

GGCCTAAAGGCGCCGGTCTTTCGTACCCCAAAATCTCGGCATTTTAAGATAAGTGAGTGTTGCGTTACACTAGCGATCTACCGCGTCTTATACTTAAGCGTATGCCCAGATCTGACTAATCGTGCCCCCGGATTAGACGGGCTTGATGGGAAAGAACAGCTCGTCTGTTTACGTATAAACAGAATCGCCTGGGTTCGC
GGGCTAAAGGTTAGGGTCTTTCACACTAAAGAGTGGTGCGTATCGTGGCTAATGTACCGCTTCTGGTATCGTGGCTTACGGCCAGACCTACAAGTACTAGACCTGAGAACTAATCTTGTCGAGCCTTCCATTGAGGGTAATGGGAGAGAACATCGAGTCAGAAGTTATTCTTGTTTACGTAGAATCGCCTGGGTCCGC


In [42]:
m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)
B = np.full([m+1,n+1], None)

print(C(m,n))
#print(T)

1346
