In [33]:
import numpy as np
subst_mat = np.array([
        [0,5,2,5],
        [5,0,5,2],
        [2,5,0,5],
        [5,2,5,0]
    ])

In [43]:
#a is the gap cost
#now we are looking for the MIN cost
import sys
def C(i,j,a):
    if T[i, j] == None:        
        dict_subst = {"A":0, "C": 1, "G":2, "T":3}
        v1,v2,v3,v4 = sys.maxsize,sys.maxsize,sys.maxsize,sys.maxsize
        if i>0 and j>0 : 
            v1 = C(i-1,j-1,a)+subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j,a)+a
        if i>=0 and j>0 : 
            v3 = C(i, j-1,a)+a
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = min(v1,v2,v3,v4)
    return T[i,j] 

In [9]:
#not working properly
def backtrack(i,j, align1,align2):
    #print(align1)
    #print(align2)    
    dict_subst = {"A":0, "C": 1, "G":2, "T":3}
    if i>0 and j>0 and T[i,j] == T[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]:   
        align1 = seq1[i-1] + align1
        align2 = seq2[j-1] + align2
        backtrack(i-1,j-1,align1,align2)
    if i>0 and j>=0 and T[i,j] == T[i-1,j]-5:        
        align1 = seq1[i-1] + align1
        align2 = "-" + align2
        backtrack(i-1,j,align1,align2)
    if i>=0 and j>0 and T[i,j] == T[i,j-1]-5:
        align1 = "-" + align1
        align2 = seq2[j-1] + align2
        backtrack(i,j-1,align1,align2) 
    return align1,align2

In [44]:
seq1 = "AATAAT"
seq2 = "AAGG"

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""

print(C(m,n,5))
print(T)
#import sys
#print(sys.maxsize)
#backtrack(m,n,align1,align2)

14
[[0 5 10 15 20]
 [5 0 5 10 15]
 [10 5 0 5 10]
 [15 10 5 5 10]
 [20 15 10 7 7]
 [25 20 15 12 9]
 [30 25 20 17 14]]


In [7]:
import Bio

In [8]:
from Bio import SeqIO
import numpy as np

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

In [9]:
seq1 = list(read_FASTA("seq1.fasta").values())[0]
seq2 = list(read_FASTA("seq2.fasta").values())[0]
print(seq1)
print(seq2)

GGCCTAAAGGCGCCGGTCTTTCGTACCCCAAAATCTCGGCATTTTAAGATAAGTGAGTGTTGCGTTACACTAGCGATCTACCGCGTCTTATACTTAAGCGTATGCCCAGATCTGACTAATCGTGCCCCCGGATTAGACGGGCTTGATGGGAAAGAACAGCTCGTCTGTTTACGTATAAACAGAATCGCCTGGGTTCGC
GGGCTAAAGGTTAGGGTCTTTCACACTAAAGAGTGGTGCGTATCGTGGCTAATGTACCGCTTCTGGTATCGTGGCTTACGGCCAGACCTACAAGTACTAGACCTGAGAACTAATCTTGTCGAGCCTTCCATTGAGGGTAATGGGAGAGAACATCGAGTCAGAAGTTATTCTTGTTTACGTAGAATCGCCTGGGTCCGC


In [10]:
m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)
B = np.full([m+1,n+1], None)

print(C(m,n))
#print(T)

1346
