In [22]:
import numpy as np
subst_mat = np.array([
        [0,5,2,5],
        [5,0,5,2],
        [2,5,0,5],
        [5,2,5,0]
    ])

## Linear Gap Cost

In [31]:
import sys
def global_linear(i,j, g):
    if T[i, j] == None:        
        dict_subst = {"a":0, "c": 1, "g":2, "t":3}
        #v1,v2,v3,v4 = 0,0,0,0
        v1,v2,v3,v4 = sys.maxsize,sys.maxsize,sys.maxsize,sys.maxsize
        if i>0 and j>0 : 
            v1 = global_linear(i-1,j-1,g)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = global_linear(i-1,j,g)+g
        if i>=0 and j>0 : 
            v3 = global_linear(i, j-1,g)+g
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = min(v1,v2,v3,v4)
    return T[i,j]

In [32]:
#Case 1
seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"   

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

print(global_linear(m,n,5))
print(T)

22
[[0 5 10 15 20 25 30 35 40 45 50 55 60]
 [5 0 5 10 15 20 25 30 35 40 45 50 55]
 [10 5 0 5 10 15 20 25 30 35 40 45 50]
 [15 10 5 0 5 10 15 20 25 30 35 40 45]
 [20 15 10 5 0 5 10 15 20 25 30 35 40]
 [25 20 15 10 5 5 5 10 15 20 25 30 35]
 [30 25 20 15 10 7 10 5 10 15 20 25 30]
 [35 30 25 20 15 10 12 10 10 15 15 20 25]
 [40 35 30 25 20 15 12 15 10 12 17 20 20]
 [45 40 35 30 25 20 17 17 15 12 17 22 20]
 [50 45 40 35 30 25 22 19 20 17 12 17 22]
 [55 50 45 40 35 30 25 24 21 20 17 17 19]
 [60 55 50 45 40 35 30 25 26 25 22 17 22]]


In [34]:
#Case 2

seq1 = "aataat"  
seq2 = "aagg"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)


print(global_linear(m,n,5))
print(T)

14
[[0 5 10 15 20]
 [5 0 5 10 15]
 [10 5 0 5 10]
 [15 10 5 5 10]
 [20 15 10 7 7]
 [25 20 15 12 9]
 [30 25 20 17 14]]


In [35]:
#Case 3

seq1 = "tccagaga"  
seq2 = "tcgat"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)


print(global_linear(m,n,5))
print(T)

20
[[0 5 10 15 20 25]
 [5 0 5 10 15 20]
 [10 5 0 5 10 15]
 [15 10 5 5 10 12]
 [20 15 10 7 5 10]
 [25 20 15 10 9 10]
 [30 25 20 15 10 14]
 [35 30 25 20 15 15]
 [40 35 30 25 20 20]]


In [36]:
#Case 4

seq1 = "ggcctaaaggcgccggtctttcgtaccccaaaatctcggcattttaagataagtgagtgttgcgttacactagcgatctaccgcgtcttatacttaagcgtatgcccagatctgactaatcgtgcccccggattagacgggcttgatgggaaagaacagctcgtctgtttacgtataaacagaatcgcctgggttcgc"  
seq2 = "gggctaaaggttagggtctttcacactaaagagtggtgcgtatcgtggctaatgtaccgcttctggtatcgtggcttacggccagacctacaagtactagacctgagaactaatcttgtcgagccttccattgagggtaatgggagagaacatcgagtcagaagttattcttgtttacgtagaatcgcctgggtccgc"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

print(global_linear(m,n,5))
print(T)

325
[[0 5 10 ... 980 985 990]
 [5 0 5 ... 975 980 985]
 [10 5 0 ... 970 975 980]
 ...
 [980 975 970 ... 325 330 335]
 [985 980 975 ... 330 325 330]
 [990 985 980 ... 333 330 325]]


In [37]:
import Bio

In [38]:
from Bio import SeqIO
import numpy as np

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

In [41]:
#case 4
seq1 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq1.fasta").values())[0].lower()
seq2 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq2.fasta").values())[0].lower()

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)


print(global_linear(m,n,5))
print(T)

325
[[0 5 10 ... 980 985 990]
 [5 0 5 ... 975 980 985]
 [10 5 0 ... 970 975 980]
 ...
 [980 975 970 ... 325 330 335]
 [985 980 975 ... 330 325 330]
 [990 985 980 ... 333 330 325]]


In [46]:
def RecurBackTrack(i,j, seq1, seq2, gap_cost, T, align1="", align2=""):
    dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    if i>0 and j>0 and T[i,j]==T[i-1,j-1]+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]] :
        align1 = seq1[i-1] + align1
        align2 = seq2[j-1] + align2
        RecurBackTrack(i-1,j-1,seq1, seq2, gap_cost, T, align1, align2)
    elif i>0 and j>=0 and T[i,j]==T[i-1,j]+ gap_cost :
        align1 = seq1[i-1] + align1
        align2 = "_" + align2
        RecurBackTrack(i-1,j,seq1, seq2, gap_cost, T, align1, align2)
    elif i>=0 and j>0 and T[i,j]==T[i,j-1]+gap_cost :
        align1 = "_" + align1
        align2 = seq2[j-1] + align2
        RecurBackTrack(i,j-1, seq1, seq2, gap_cost, T, align1, align2)
    else:
        print (align1, align2)
        return None

In [47]:
#Case 1
seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

22
acgt_gtcaacgt acgtcgt_agcta
None


In [48]:
#project2_eval.txt Question 1
#seq1 and seq2

seq1 = "tatggagagaataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtggaccatatggccataatcaaaaag"  
seq2 = "atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

226
tatgga_gagaataaaagaactgagagatct_aatgtcgcagtcccgcac_tcgcgagatact_cactaagac_cactgtggaccatatggccataatcaaaaag _atggatgtcaatccga_ctctacttttcctaaaaattccagcgcaaaatgccataag_caccacattcccttatactggagatcct_cca_tacagccatggaa
None


In [50]:
#project2_eval.txt Question 3
#seq1 and seq3

seq1 = "tatggagagaataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtggaccatatggccataatcaaaaag"  
seq2 = "tccaaaatggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagcttgcggaaaaggcaatgaaagaatatggggaagatccgaaaatcgaaa" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

206
tatggagagaataaaaga_actgagagatctaatgtcgcagtcccgcactcg_cgagatactcactaagaccactgtggaccatatggccataat_c__aaa___aag t_c_ca_a_aatggaagactttgtgcga_c_aatgcttcaatccaatgatcgtcgagct_tgcggaaaaggcaatg_aaagaatatggggaagatccgaaaatcgaaa
None


In [51]:
#project2_eval.txt Question 3
#seq1 and seq4

seq1 = "tatggagagaataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtggaccatatggccataatcaaaaag"  
seq2 = "aaaagcaacaaaaatgaaggcaatactagtagttctgctatatacatttgcaaccgcaaatgcagacacattatgtataggttatcatgcgaacaattca" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

202
_tatg_ga_gagaataaaag__a_actgagagatctaatgt_cgcagtcccgcactcgcgagatactcactaagaccac_tgtggaccat_atggccataatcaaaaag aaaagcaacaaaaatgaaggcaatactagtagttctgctatataca_t_ttgcaaccgc_aaatgcagac__acattatgtataggttatcat_g_cg_aa_caattca
None


In [52]:
#project2_eval.txt Question 3
#seq1 and seq5

seq1 = "tatggagagaataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtggaccatatggccataatcaaaaag"  
seq2 = "atgagtgacatcgaagccatggcgtctcaaggcaccaaacgatcatatgaacaaatggagactggtggggagcgccaggatgccacagaaatcagagcat" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

209
tatggagaga_ataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtgga___cca_tatggc_ca_taatcaaaa_ag _at_gagtgacatcgaag__ccatggcgtctcaag__gca_ccaaacgatcatatga_acaaatggagactggtggggagcgccaggatgccacagaaatcagagcat
None


In [53]:
#project2_eval.txt Question 3
#seq2 and seq3

seq1 = "atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa"  
seq2 = "tccaaaatggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagcttgcggaaaaggcaatgaaagaatatggggaagatccgaaaatcgaaa" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

239
______atggatg__tcaatccgactctacttt_tcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa tccaaaatggaagactttgtgcgacaatgcttcaatccaatga_t_cgtcg_agcttg_cggaaaaggca_atgaaagaata_tggggaagatccg_aaaatc__gaaa
None


In [54]:
#project2_eval.txt Question 3
#seq2 and seq4

seq1 = "atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa"  
seq2 = "aaaagcaacaaaaatgaaggcaatactagtagttctgctatatacatttgcaaccgcaaatgcagacacattatgtataggttatcatgcgaacaattca" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

223
atggatgtcaatccgactcta_cttttcctaaaaattccagcgca_aaatgccataa__gc_accacattc_ccttatactggagatcctccatac_agccatggaa a_aaa_g_caacaaaaatgaaggcaatactagtagttctgctatatacat_ttgcaaccgcaaatgcagacacattatg_tataggttat_catgcgaacaat_tca
None


In [55]:
#project2_eval.txt Question 3
#seq2 and seq5

seq1 = "atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa"  
seq2 = "atgagtgacatcgaagccatggcgtctcaaggcaccaaacgatcatatgaacaaatggagactggtggggagcgccaggatgccacagaaatcagagcat" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

220
atggatgtcaatccgactctacttttcctaaaaattcc_agcg_caaaatgccataagcaccacattcccttata_c_tggagatcctccatacagccatgg_aa atgagtgac_at_cgaagccatggcgtctcaaggcaccaaacgatcatatg_aacaaatg_gagactggtggggagcgccaggatgccacaga_aatcagagcat
None


In [56]:
#project2_eval.txt Question 3
#seq3 and seq4

seq1 = "tccaaaatggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagcttgcggaaaaggcaatgaaagaatatggggaagatccgaaaatcgaaa"  
seq2 = "aaaagcaacaaaaatgaaggcaatactagtagttctgctatatacatttgcaaccgcaaatgcagacacattatgtataggttatcatgcgaacaattca" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

219
tccaaaatggaagactttgtgcgacaatgct_tcaa_tccaatg_at_cg_tcg_agcttgcgga_aaaggca_atgaaagaatatggggaagatccgaa_aatcgaaa __aaaagcaacaaa_aatg_aaggcaatactagtagttctgctatatacatttgcaac_cgcaaatgcagacacat_tatgtata_ggttatcatgcgaacaatt__ca
None


In [57]:
#project2_eval.txt Question 3
#seq3 and seq5

seq1 = "tccaaaatggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagcttgcggaaaaggcaatgaaagaatatggggaagatccgaaaatcgaaa"  
seq2 = "atgagtgacatcgaagccatggcgtctcaaggcaccaaacgatcatatgaacaaatggagactggtggggagcgccaggatgccacagaaatcagagcat" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

205
_t__ccaaaatggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagcttgcggaaaaggcaatgaaagaatatggggaagatccgaaaatc_gaa_a_ atgagtgacatcgaagccatggcgtctcaaggcaccaa_acgatcat_at_gaacaaatgg_aga_ctggtg_gggagcgccaggatgccacagaaatcagagcat
None


In [58]:
#project2_eval.txt Question 3
#seq4 and seq5

seq1 = "aaaagcaacaaaaatgaaggcaatactagtagttctgctatatacatttgcaaccgcaaatgcagacacattatgtataggttatcatgcgaacaattca"  
seq2 = "atgagtgacatcgaagccatggcgtctcaaggcaccaaacgatcatatgaacaaatggagactggtggggagcgccaggatgccacagaaatcagagcat" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

print(RecurBackTrack(m,n, seq1, seq2, 5, T))

210
aaaagcaaca__aaaatgaaggcaatactagtagttctgctatatacatt_tgcaaccgcaaatgcagac__acattatgta_taggttatcatgcgaa_caattca_ atgagtgacatcgaagccatggc_gt_ctca_ag_gc_accaaacg_atcatatga__acaaatggagactggtggggagcgccaggatgccacagaaatcagagcat
None


In [59]:
def read_subst_mtrx(filename):
    subst_mat = np.zeros((4,4))
    #skipping the first line
    f = open(filename,'r')
    f.readline()
    for i in range(0,4):
        line = f.readline()
        nums_in_line = line.split()
        for j in range(1,4):
            subst_mat[i,j-1] = nums_in_line[j]
    f.close()
    return subst_mat  

In [60]:
subst_mat = read_subst_mtrx("/Users/chandnishaw/Downloads/subst_matrix.txt")
print(subst_mat)

[[0. 5. 2. 0.]
 [5. 0. 5. 0.]
 [2. 5. 0. 0.]
 [5. 2. 5. 0.]]


In [61]:
def read_subst_mtrx(filename):
    opt_score = np.zeros((5,5))
    #skipping the first line
    f = open(filename,'r')
    f.readline()
    for i in range(0,5):
        line = f.readline()
        nums_in_line = line.split()
        for j in range(1,6):
            opt_score[i,j-1] = nums_in_line[j]
    f.close()
    return opt_score  

In [62]:
opt_score = read_subst_mtrx("/Users/chandnishaw/Desktop/AiB/Project2/optimal_score.txt")
print(opt_score)

[[  0. 226. 206. 202. 209.]
 [226.   0. 239. 223. 220.]
 [206. 239.   0. 219. 205.]
 [202. 223. 219.   0. 210.]
 [209. 220. 205. 210.   0.]]


## Affine Gap cost

In [26]:
def global_affine_cost(seq1, seq2, a,b):
    dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    m = len(seq1)
    n = len(seq2)
    
    for i in range(0, m+1):
        for j in range(0, n+1):
        # Compute D[i,j]
            v1,v2 = sys.maxsize,sys.maxsize
            if i>0 and j>=0 : 
                v1 = S[i-1,j]+(a+b)
            if i>1 and j>=0:
                v2 = D[i-1,j]+a
            D[i,j] = min(v1,v2)
                    
        # Compute I[i,j]
            v1,v2 = sys.maxsize,sys.maxsize
            if i>=0 and j>0:
                v1 = S[i,j-1]+(a+b)
            if i>=0 and j>1:
                v2 = I[i,j-1]+a
            I[i,j] = min(v1,v2)
                 
        # Compute S[i,j] 
            v1,v2,v3,v4 = sys.maxsize,sys.maxsize,sys.maxsize,sys.maxsize
            if i==0 and j==0 :
                v1 = 0                
            if i>0 and j>0:
                v2 = S[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
            if i>0 and j>=0:
                v3 = D[i,j]
            if i>=0 and j>0:
                v4 = I[i,j]
            S[i,j] = min(v1,v2,v3,v4)        
    return S[i,j]

In [27]:
def backtrack_affine(seq1, seq2, a, b):
    i = len(seq1)
    j = len(seq2)
    align1 = ""
    align2 = ""
    dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    while (i>0 or j>0):
        if (i>0 and j>0) and (S[i,j] == S[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]):
            align1 = seq1[i-1] + align1
            align2 = seq2[j-1] + align2
            i = i-1
            j = j-1
        else:
            k = 1
            while True:
                if i>=k and S[i,j] == S[i-k,j] + (a+b*k):
                    l = i
                    while(l>=i-k+1):
                        align1 = seq1[l-1] + align1
                        align2 = "-" + align2
                        l = l-1
                    i = i-k
                    break
                elif j>=k and S[i,j] == S[i,j-k] + (a+b*k):
                    l = j
                    while(l>=i-k+1):
                        align1 = "-" + align1
                        align2 = seq2[l-1] + align2
                        l = l-1
                    j = j-k
                    break
                else:
                    k = k+1
    f = open('alignment_with_affine_gap_cost.fasta','w')
    f.write(">Seq1 \n")
    f.write(align1)
    f.write("\n \n>Seq2 \n")
    f.write(align2)
    f.close()
    return align1, align2

In [28]:
#case 2
seq1 = "aataat"
seq2 = "aagg"

m = len(seq1)
n = len(seq2)

S = np.full([m+1,n+1], None)
I = np.full([m+1,n+1], None)
D = np.full([m+1,n+1], None)

print(global_affine_cost(seq1, seq2, 5,5))
print(S)
print(backtrack_affine(seq1, seq2, 5,5))

22
[[0 10 15 20 25]
 [10 0 10 15 20]
 [15 10 0 10 15]
 [20 15 10 5 15]
 [25 20 15 12 7]
 [30 25 20 17 14]
 [35 30 25 25 22]]
('aataat', 'a--agg')


In [29]:
#case 3
seq1 = "tccagaga"
seq2 = "tcgat"

m = len(seq1)
n = len(seq2)

S = np.full([m+1,n+1], None)
I = np.full([m+1,n+1], None)
D = np.full([m+1,n+1], None)

print(global_affine_cost(seq1, seq2, 5,5))
print(S)
print(backtrack_affine(seq1, seq2, 5,5))

29
[[0 10 15 20 25 30]
 [10 0 10 15 20 25]
 [15 10 0 10 15 20]
 [20 15 10 5 15 17]
 [25 20 15 12 5 15]
 [30 25 20 15 14 10]
 [35 30 25 22 15 19]
 [40 35 30 25 24 20]
 [45 40 35 32 25 29]]
('tccagaga', 'tc---gat')


In [30]:
#project2_eval.txt Question 2

seq1 = "tatggagagaataaaagaactgagagatctaatgtcgcagtcccgcactcgcgagatactcactaagaccactgtggaccatatggccataatcaaaaag"
seq2 = "atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaatgccataagcaccacattcccttatactggagatcctccatacagccatggaa"

m = len(seq1)
n = len(seq2)

S = np.full([m+1,n+1], None)
I = np.full([m+1,n+1], None)
D = np.full([m+1,n+1], None)

print(global_affine_cost(seq1, seq2, 5,5))
print(S)
print(backtrack_affine(seq1, seq2, 5,5))

266
[[0 10 15 ... 495 500 505]
 [10 5 10 ... 495 500 505]
 [15 10 10 ... 490 495 500]
 ...
 [495 490 490 ... 264 269 268]
 [500 495 495 ... 274 264 269]
 [505 502 500 ... 277 274 266]]
('tatggagagaataaaagaactgagagatct-aatgtcgcagtcccgcac--tcgcgagatactcactaagac---cactgtggaccatatggccataatcaaaaag', '-atggatgtcaatccgactctacttttcctaaaaattccagcgcaaaattgccataagcaccacattcccttttatactggagatcctcca--tacagccatggaa')
