In [55]:
import numpy as np
subst_mat = np.array([
        [0,5,2,5],
        [5,0,5,2],
        [2,5,0,5],
        [5,2,5,0]
    ])

In [56]:
import sys
def global_linear(i,j, g):
    if T[i, j] == None:        
        dict_subst = {"a":0, "c": 1, "g":2, "t":3}
        #v1,v2,v3,v4 = 0,0,0,0
        v1,v2,v3,v4 = sys.maxsize,sys.maxsize,sys.maxsize,sys.maxsize
        if i>0 and j>0 : 
            v1 = global_linear(i-1,j-1,g)+ subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = global_linear(i-1,j,g)+g
        if i>=0 and j>0 : 
            v3 = global_linear(i, j-1,g)+g
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = min(v1,v2,v3,v4)
    return T[i,j]

In [57]:
#Case 1
seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"   

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

print(global_linear(m,n,5))
print(T)

22
[[0 5 10 15 20 25 30 35 40 45 50 55 60]
 [5 0 5 10 15 20 25 30 35 40 45 50 55]
 [10 5 0 5 10 15 20 25 30 35 40 45 50]
 [15 10 5 0 5 10 15 20 25 30 35 40 45]
 [20 15 10 5 0 5 10 15 20 25 30 35 40]
 [25 20 15 10 5 5 5 10 15 20 25 30 35]
 [30 25 20 15 10 7 10 5 10 15 20 25 30]
 [35 30 25 20 15 10 12 10 10 15 15 20 25]
 [40 35 30 25 20 15 12 15 10 12 17 20 20]
 [45 40 35 30 25 20 17 17 15 12 17 22 20]
 [50 45 40 35 30 25 22 19 20 17 12 17 22]
 [55 50 45 40 35 30 25 24 21 20 17 17 19]
 [60 55 50 45 40 35 30 25 26 25 22 17 22]]


In [51]:
#code from Alzbeta
#a is the gap cost
#now we are looking for the MIN cost
import sys
def C(i,j,a):
    if T[i, j] == None:        
        dict_subst = {"a":0, "c": 1, "g":2, "t":3}
        v1,v2,v3,v4 = sys.maxsize,sys.maxsize,sys.maxsize,sys.maxsize
        if i>0 and j>0 : 
            v1 = C(i-1,j-1,a)+subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
        if i>0 and j>=0 : 
            v2 = C(i-1,j,a)+a
        if i>=0 and j>0 : 
            v3 = C(i, j-1,a)+a
        if i==0 and j==0 : 
            v4 = 0
        T[i,j] = min(v1,v2,v3,v4)
    return T[i,j] 

In [54]:
#Case 1

seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

#print(global_linear(m,n))

print(C(m,n,5))
print(T)

KeyError: 'a'

In [8]:
#Case 2

seq1 = "aataat"  
seq2 = "aagg"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

#print(global_linear(m,n))

print(C(m,n,5))
print(T)

14
[[0 5 10 15 20]
 [5 0 5 10 15]
 [10 5 0 5 10]
 [15 10 5 5 10]
 [20 15 10 7 7]
 [25 20 15 12 9]
 [30 25 20 17 14]]


In [9]:
#Case 3

seq1 = "tccagaga"  
seq2 = "tcgat"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

#print(global_linear(m,n))

print(C(m,n,5))
print(T)

20
[[0 5 10 15 20 25]
 [5 0 5 10 15 20]
 [10 5 0 5 10 15]
 [15 10 5 5 10 12]
 [20 15 10 7 5 10]
 [25 20 15 10 9 10]
 [30 25 20 15 10 14]
 [35 30 25 20 15 15]
 [40 35 30 25 20 20]]


In [16]:
#Case 4

seq1 = "ggcctaaaggcgccggtctttcgtaccccaaaatctcggcattttaagataagtgagtgttgcgttacactagcgatctaccgcgtcttatacttaagcgtatgcccagatctgactaatcgtgcccccggattagacgggcttgatgggaaagaacagctcgtctgtttacgtataaacagaatcgcctgggttcgc"  
seq2 = "gggctaaaggttagggtctttcacactaaagagtggtgcgtatcgtggctaatgtaccgcttctggtatcgtggcttacggccagacctacaagtactagacctgagaactaatcttgtcgagccttccattgagggtaatgggagagaacatcgagtcagaagttattcttgtttacgtagaatcgcctgggtccgc"  

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

#print(global_linear(m,n))

print(C(m,n,5))
print(T)

325
[[0 5 10 ... 980 985 990]
 [5 0 5 ... 975 980 985]
 [10 5 0 ... 970 975 980]
 ...
 [980 975 970 ... 325 330 335]
 [985 980 975 ... 330 325 330]
 [990 985 980 ... 333 330 325]]


In [19]:
import Bio

In [20]:
from Bio import SeqIO
import numpy as np

def read_FASTA(filename):
    records_dict = {}
    for seq_record in SeqIO.parse(filename, "fasta"):
        records_dict[seq_record.id] = seq_record.seq        
    return records_dict

In [21]:
#case 4
seq1 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq1.fasta").values())[0]
seq2 = list(read_FASTA("/Users/chandnishaw/Desktop/AiB/Project1/seq2.fasta").values())[0]

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

#print(global_linear(m,n))

print(C(m,n,5))
print(T)

325
[[0 5 10 ... 980 985 990]
 [5 0 5 ... 975 980 985]
 [10 5 0 ... 970 975 980]
 ...
 [980 975 970 ... 325 330 335]
 [985 980 975 ... 330 325 330]
 [990 985 980 ... 333 330 325]]


In [41]:
def RecurBackTrack(i,j, align1,align2, gapcost):
    print(align1)
    print(align2)
   
    dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    if i>0 and j>0 and T[i,j] == T[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]:   
        align1 = seq1[i-1] + align1
        align2 = seq2[j-1] + align2 
        RecurBackTrack(i-1,j-1,align1,align2,gapcost)
    if i>0 and j>=0 and T[i,j] == T[i-1,j]+gapcost:        
        align1 = seq1[i-1] + align1
        align2 = "-" + align2 
        RecurBackTrack(i-1,j,align1,align2,gapcost)
    if i>=0 and j>0 and T[i,j] == T[i,j-1]+gapcost:
        align1 = "-" + align1
        align2 = seq2[j-1] + align2
        RecurBackTrack(i,j-1,align1,align2,gapcost) 
    return "hello"

In [42]:
seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta" 

m = len(seq1)
n = len(seq2)

T = np.full([m+1,n+1], None)

align1 = ""
align2 = ""


print(global_linear(m,n,5))

RecurBackTrack(m,n,align1,align2, -1)

22


t
a
gt
ta
cgt
cta
acgt
gcta
aacgt
agcta


'hello'

In [196]:
def global_affine(i,j):
    if S[i, j] and D[i, j] and I[i, j] == None:   
        dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    
    for i in range(0, m):
        for j in range(0, n):
        # Compute D[i,j]
            v1,v2 = 0,0
            if i>0 and j>0 : 
                v1 = S[i-1,j]-10
            if i>1 and j>=0:
                v2 = D[i-1,j]-5
            D[i,j] = max(v1,v2)
            return D[i,j]
            
        # Compute I[i,j]
            v1, v2 = 0, 0
            if i>=0 and j>0:
                v1 = S[i-1,j]-10
            if i>=0 and j>1:
                v2 = I[i,j-1]-5
            I[i,j] = max(v1,v2)
            return I[i,j]
        
        # Compute S[i,j]
            v1,v2,v3,v4 = 0,0,0,0
            if i==0 and j==0 : 
                v1 = 0
            if i>0 and j>0:
                v2 = S[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
            if i>0 and j>=0:
                v3 = D[i,j]
            if i>=0 and j>0:
                v4 = I[i,j]
            S[i,j] = max(v1,v2,v3,v4)
            return S[i,j]
        
        
    #return D[i,j], I[i,j], S[i,j]

In [197]:
#Case 1

seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"  

m = len(seq1)
n = len(seq2)

D = np.full([m+1,n+1], None)
I = np.full([m+1,n+1], None)
S = np.full([m+1,n+1], None)

print(global_affine(m,n))

0


In [198]:
D

array([[0, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, None, None, None, None,
        None, None],
       [None, None, None, None, None, None, None, Non

In [202]:
import numpy as np
subst_mat = np.array([
        [0,5,2,5],
        [5,0,5,2],
        [2,5,0,5],
        [5,2,5,0]
    ])

In [205]:
def global_affine(i,j, seq1, seq2, a, b):
    if S[i, j] and D[i, j] and I[i, j] == None:   
        global dict_subst
        dict_subst = {"a":0, "c": 1, "g":2, "t":3}
    
    for i in range(0, m):
        for j in range(0, n):
        # Compute D[i,j]
            v1,v2 = 0,0
            if i>0 and j>0 : 
                v1 = S[i-1,j]-(a+b)
            if i>1 and j>=0:
                v2 = D[i-1,j]-a
            D[i,j] = max(v1,v2)
            
        # Compute I[i,j]
            v1, v2 = 0, 0
            if i>=0 and j>0:
                v1 = S[i,j-1]-(a+b)
            if i>=0 and j>1:
                v2 = I[i,j-1]-a
            I[i,j] = max(v1,v2)
        
        # Compute S[i,j]
            v1,v2,v3,v4 = 0,0,0,0
            if i==0 and j==0 : 
                v1 = 0
            if i>0 and j>0:
                #v2 = S[i-1,j-1] + s(A[i],B[j])
                v2 = S[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
            if i>0 and j>=0:
                v3 = D[i,j]
            if i>=0 and j>0:
                v4 = I[i,j]
            S[i,j] = max(v1,v2,v3,v4)
        
        
    return D[i,j], I[i,j], S[i,j]

In [206]:
#Case 1

seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"  

m = len(seq1)
n = len(seq2)

D = np.full([m+1,n+1], None)
I = np.full([m+1,n+1], None)
S = np.full([m+1,n+1], None)

print(global_affine(m,n,seq1, seq2, 5, 5))

NameError: name 'dict_subst' is not defined

In [191]:
seq1 = "acgtgtcaacgt"  
seq2 = "acgtcgtagcta"  

i, j = 1, 1

def global_affine(i,j, seq1, seq2, a, b):
    
    for i in range(1, len(seq1)+1):
        # Compute D[i,j]
                d1 = S[i-1,0] - (a+b)
                d2 = D[i-1,0] - a
                D[i,0] = max(d1, d2)
            
                S[i,0] = D[i,0]
    
    for j in range(1, len(seq2)+1):
        # Compute I[i,j]
                i1 = S[0,j-1]-(a+b)
                i2 = I[0,j-1]-a
                I[0,j] = max(i1,i2)
            
                S[0,j] =  I[0,j]
            
            
    for j in range(1, len(seq2)+1):
        for i in range(1, len(seq1)+1):
        # Compute S[i,j]
                d1 = S[i-1,j]-(a+b)
                d2 = D[i-1,0]-a
                D[i,j] = max(v1,v2)
            
                i1 = S[i,j-1]-(a+b)
                i2 = I[i,j-1]-a
                I[i,j] = max(i1,i2)
        
                s1 = S[i-1,j-1] + subst_mat[dict_subst[seq1[i-1]], dict_subst[seq2[j-1]]]
                S[i,j] = max(D[i,j], I[i,j], s1)
            
    return(S, D, I, S[-1,-1])

            
print(global_affine(i, j, seq1, seq2, 5, 5))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

In [60]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
alignment = MultipleSeqAlignment(
         [
            SeqRecord(Seq("ACTCCTA"), id='seq1'),
            SeqRecord(Seq("AAT-CTA"), id='seq2'),
            SeqRecord(Seq("CCTACT-"), id='seq3'),
            SeqRecord(Seq("TCTCCTC"), id='seq4'),
         ]
                                    )

In [61]:
print(alignment)

Alignment with 4 rows and 7 columns
ACTCCTA seq1
AAT-CTA seq2
CCTACT- seq3
TCTCCTC seq4


In [62]:
substitutions = alignment.substitutions
print(substitutions)

    A    C    T
A 2.0  4.5  1.0
C 4.5 10.0  0.5
T 1.0  0.5 12.0



In [63]:
m = substitutions.select("ATCG")
print(m)

    A    T    C   G
A 2.0  1.0  4.5 0.0
T 1.0 12.0  0.5 0.0
C 4.5  0.5 10.0 0.0
G 0.0  0.0  0.0 0.0

