In [118]:
import numpy as np
import sys
import pandas as pd

In [119]:
#Distance matrix

def read_mtrx(filename):
    f = open(filename,'r')
    num_species = int(f.readline())

    dict_mat = {}
    mat = np.zeros((num_species,num_species))
    
    for i in range(0,num_species):
        line = f.readline()
        nums_in_line = line.split()
        dict_mat[nums_in_line[0]] = i
        for j in range(1,num_species +1):
            mat[i,j-1] = nums_in_line[j]
    f.close()
    return dict_mat, mat 

In [120]:
species_dict, dist = read_mtrx("C:\\Users\\awila\\Downloads\\example_slide4.phy")
print(species_dict)
print(dist)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}
[[0.   0.23 0.16 0.2  0.17]
 [0.23 0.   0.23 0.17 0.24]
 [0.16 0.23 0.   0.2  0.11]
 [0.2  0.17 0.2  0.   0.21]
 [0.17 0.24 0.11 0.21 0.  ]]


In [121]:
species = list(species_dict.keys())
species

['A', 'B', 'C', 'D', 'E']

In [122]:
list(species_dict.keys())

['A', 'B', 'C', 'D', 'E']

In [123]:
dict_dist= {}
for i in range(len(species)) :
    dict_dist[species[i]] = dist[i]
dict_dist

{'A': array([0.  , 0.23, 0.16, 0.2 , 0.17]),
 'B': array([0.23, 0.  , 0.23, 0.17, 0.24]),
 'C': array([0.16, 0.23, 0.  , 0.2 , 0.11]),
 'D': array([0.2 , 0.17, 0.2 , 0.  , 0.21]),
 'E': array([0.17, 0.24, 0.11, 0.21, 0.  ])}

In [124]:
dist=pd.DataFrame.from_dict(dict_dist,
orient='index', columns=species)
print(dist)

      A     B     C     D     E
A  0.00  0.23  0.16  0.20  0.17
B  0.23  0.00  0.23  0.17  0.24
C  0.16  0.23  0.00  0.20  0.11
D  0.20  0.17  0.20  0.00  0.21
E  0.17  0.24  0.11  0.21  0.00


In [125]:
dist.drop("A")

A     B     C     D     E
B  0.23  0.00  0.23  0.17  0.24
C  0.16  0.23  0.00  0.20  0.11
D  0.20  0.17  0.20  0.00  0.21
E  0.17  0.24  0.11  0.21  0.00

In [126]:
dist.loc['D','B']

0.17

In [127]:
dist.size

25

In [128]:
##Step 1: dataframe to find two neighbours

N = pd.DataFrame(columns=species, index = species)
N

A    B    C    D    E
A  NaN  NaN  NaN  NaN  NaN
B  NaN  NaN  NaN  NaN  NaN
C  NaN  NaN  NaN  NaN  NaN
D  NaN  NaN  NaN  NaN  NaN
E  NaN  NaN  NaN  NaN  NaN

In [129]:
def step1(dist):
    S = len(dist.columns)
    N = pd.DataFrame(columns=dist.columns, index = dist.index)
    ris = []
    for i in dist.index:
        ri = 0
        for j in dist.columns:
            ri +=dist.loc[i,j]
        ris.append(ri/(S-2))
    
    rjs = []
    for j in dist.columns:
        rj = 0
        for i in dist.index:
            rj +=dist.loc[i,j]
        rjs.append(rj/(S-2))
        
    minN = sys.maxsize
    mini = dist.index[0]
    minj = dist.columns[0]
    for i in range(len(dist.index)):
        for j in range(len(dist.columns)):
            ci = dist.index[i]
            cj = dist.columns[j]
            nij = dist.loc[ci,cj]-ris[i]-rjs[j]
            N.loc[ci,cj]=nij
            if ci != cj:
                if nij<minN : 
                    minN = nij
                    mini = ci
                    minj = cj
    return(mini,minj,minN)

In [130]:
step1(dist)

('B', 'D', -0.38)

In [70]:
#Step 2: Adding a new node k

species_dict, dist = read_mtrx("C:\\Users\\awila\\Downloads\\example_slide4.phy")
print(species_dict)
print(dist)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}
[[0.   0.23 0.16 0.2  0.17]
 [0.23 0.   0.23 0.17 0.24]
 [0.16 0.23 0.   0.2  0.11]
 [0.2  0.17 0.2  0.   0.21]
 [0.17 0.24 0.11 0.21 0.  ]]


In [71]:
species = list(species_dict.keys())
species

['A', 'B', 'C', 'D', 'E']

In [73]:
node_list = list(species_dict.keys())
node_list

['A', 'B', 'C', 'D', 'E']

In [74]:
node_list = list(species_dict.keys())
node_list.remove(species[mini])
node_list.remove(species[minj])
node_list.append('('+species[mini]+','+species[minj]+')')
node_list

ValueError: list.remove(x): x not in list

In [41]:
def step2(mini,minj,node_list):
    nodes = node_list.copy()
    node_list.remove(nodes[mini])
    node_list.remove(nodes[minj])
    node_list.append('('+nodes[mini]+','+nodes[minj]+')')
    return node_list

In [75]:
step2(mini,minj,node_list)

ValueError: list.remove(x): x not in list