In [2]:
import numpy as np
import pandas as pd

# Distance matrix

In [3]:
#an improved version of the read_subst_mtrx from project_3
#returns the matrix and a dictionary mapping the species name to indeces
def read_mtrx(filename):
    f = open(filename,'r')
    num_species = int(f.readline())

    dict_mat = {}
    mat = np.zeros((num_species,num_species))
    
    for i in range(0,num_species):
        line = f.readline()
        nums_in_line = line.split()
        dict_mat[nums_in_line[0]] = i
        for j in range(1,num_species +1):
            mat[i,j-1] = nums_in_line[j]
    f.close()
    return dict_mat, mat 

In [4]:
species_dict, dist = read_mtrx("C:/Users/lenab/Documents/AU/Algorithms_in_bioinformatics/Brouillons_projets/example_slide4.phy")
print(species_dict)
print(dist)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}
[[0.   0.23 0.16 0.2  0.17]
 [0.23 0.   0.23 0.17 0.24]
 [0.16 0.23 0.   0.2  0.11]
 [0.2  0.17 0.2  0.   0.21]
 [0.17 0.24 0.11 0.21 0.  ]]


In [5]:
species = list(species_dict.keys())
dict_dist = {}
for i in range(len(species)) :
    dict_dist[species[i]] = dist[i]
dict_dist

{'A': array([0.  , 0.23, 0.16, 0.2 , 0.17]),
 'B': array([0.23, 0.  , 0.23, 0.17, 0.24]),
 'C': array([0.16, 0.23, 0.  , 0.2 , 0.11]),
 'D': array([0.2 , 0.17, 0.2 , 0.  , 0.21]),
 'E': array([0.17, 0.24, 0.11, 0.21, 0.  ])}

In [12]:
dist=pd.DataFrame.from_dict(dict_dist,
orient='index', columns=species)
print(dist)

      A     B     C     D     E
A  0.00  0.23  0.16  0.20  0.17
B  0.23  0.00  0.23  0.17  0.24
C  0.16  0.23  0.00  0.20  0.11
D  0.20  0.17  0.20  0.00  0.21
E  0.17  0.24  0.11  0.21  0.00


In [16]:
dist.loc['A','B']

0.23

# NJ algorithm

## Step 1

In [8]:
N = pd.DataFrame(columns=species, index = species)
N

A    B    C    D    E
A  NaN  NaN  NaN  NaN  NaN
B  NaN  NaN  NaN  NaN  NaN
C  NaN  NaN  NaN  NaN  NaN
D  NaN  NaN  NaN  NaN  NaN
E  NaN  NaN  NaN  NaN  NaN

In [23]:
dist.loc['A','B']

0.23

In [24]:
current_nodes = species.copy
def step1(dist):
    S = len(dist.columns)
    N = pd.DataFrame(columns=dist.columns, index = dist.index)
    ris = []
    for i in dist.index:
        ri = 0
        for j in dist.columns:
            ri +=dist.loc[i,j]
        ris.append(ri/(S-2))
    
    rjs = []
    for j in dist.columns:
        rj = 0
        for i in dist.index:
            rj +=dist.loc[i,j]
        rjs.append(rj/(S-2))
        
    minN = dist.loc[dist.columns[0],dist.index[0]]-ris[0]-rjs[0]
    mini = 0
    minj = 0
    for i in range(len(dist.index)):
        for j in range(len(dist.columns)):
            ci = dist.index[i]
            cj = dist.columns[j]
            nij = dist.loc[i,j]+ris[i]+rjs[j]
            N.loc[i,j]=nij
            if nij<minN : 
                minN = nij
                mini = i
                minj = j
    return(mini,minj,minN)
        

In [25]:
step1(dist)

TypeError: list indices must be integers or slices, not str